// TodoMVC/React/app/modules/App.jsx
/**
 * Created by 78462 on 2017/4/23.
 */
import React, { Component } from 'react';
import config from './config';
import Item from './Item';
import Footer from './Footer';
import { Router } from '../../dist/director/build/director';

class App extends Component {
    constructor() {
        super();
        this.state = {
            nowShowing: config.ALL,
            editing: null,
            newTodo: ''
        };
    }

    componentDidMount() {
        let setState = this.setState,
            router = Router({
                '/': setState.bind(this, {nowShowing: config.ALL}),
                '/active': setState.bind(this, {nowShowing: config.ACTIVE}),
                '/completed': setState.bind(this, {nowShowing: config.COMPLETED})
            });
        router.init('/');
    }

    handleChange(event) {
        this.setState({
            newTodo: event.target.value
        });
    }

    handleNewTodoKeyDown(event) {
        if (event.keyCode !== config.ENTER_KEY) {
            return;
        }

        event.preventDefault();

        var val = this.state.newTodo.trim();

        if (val) {
            this.props.model.addTodo(val);
            this.setState({newTodo: ''});
        }
    }

    toggleAll(event) {
        let target = event.target;
        this.props.model.toggleAll(target.checked);
    }

    toggle(todoToToggle) {
        this.props.model.toggle(todoToToggle);
    }

    destroy(todo) {
        this.props.model.destroy(todo);
    }

    edit(todo) {
        this.setState({
            editing: todo.id
        });
    }

    save(todoToSave, text) {
        this.props.model.save(todoToSave, text);
        this.setState({
            editing: null
        });
    }

    cancel() {
        this.setState({
            editing: null
        });
    }

    clearCompleted() {
        this.props.model.clearCompleted();
    }

    render() {
        let footer, main;
        let todos = this.props.model.todos;

        let showTodos = todos.filter((todo) =>{
            switch (this.state.nowShowing) {
                case config.ACTIVE:
                    return !todo.completed;
                case config.COMPLETED:
                    return todo.completed;
                default:
                    return true;
            }
        });

        let todoItems = showTodos.map(function(todo){
            return (
                <Item
                    key={todo.id}
                    todo={todo}
                    onToggle={this.toggle.bind(this, todo)}
                    onDestroy={this.destroy.bind(this, todo)}
                    onEdit={this.edit.bind(this, todo)}
                    editing={this.state.editing === todo.id}
                    onSave={this.save.bind(this, todo)}
                    onCancel={this.cancel.bind(this)}
                    />
            );
        }, this);

        let activeTodoCount = todos.reduce(function(accum, todo) {
            return todo.completed ? accum : accum + 1;
        }, 0);

        let completedCount = todos.length - activeTodoCount;

        if (activeTodoCount || completedCount) {
            footer =
                <Footer
                    count={activeTodoCount}
                    completedCount={completedCount}
                    nowShowing={this.state.nowShowing}
                    onClearCompleted={this.clearCompleted.bind(this)}
                    />;

            main = (
                <section className="main">
                    <input
                        className="toggle-all"
                        type="checkbox"
                        onChange={this.toggleAll.bind(this)}
                        checked={activeTodoCount === 0}
                        />
                    <ul className="todo-list">
                        {todoItems}
                    </ul>
                </section>
            );
        }

        return (
            <div>
                <header className="header">
                    <h1>todos</h1>
                    <input
                        className="new-todo"
                        placeholder="What needs to be done?"
                        value={this.state.newTodo}
                        onKeyDown={this.handleNewTodoKeyDown.bind(this)}
                        onChange={this.handleChange.bind(this)}
                        autoFocus={true}
                        />
                </header>
                {main}
                {footer}
            </div>
        );
    }
}

export default App;

// TodoMVC/Vue/src/components/App.vue
<template>
    <section class="todoapp">
      <header class="header">
        <h1>todos</h1>
        <input class="new-todo" autofocus autocomplete="off" placeholder="What needs to be done?" v-model="newTodo" @keyup.enter="addTodo">
      </header>
      <section class="main" v-show="todos.length">
        <input class="toggle-all" type="checkbox" v-model="allDone">
        <ul class="todo-list">
          <li is="todo-item" v-for="todo in filteredTodos" :todo="todo" :key="todo.key" :editing="editing"></li>
        </ul>
      </section>
      <todo-footer :todos="todos" :remaining="remaining" :visibility="visibility"></todo-footer>
    </section>
</template>

<script type="text/ecmascript-6">
  import todoItem from './Item.vue';
  import todoFooter from './Footer.vue';
  import bus from '../bus';
  import utils from '../utils';

  let uuid = utils.uuid, filters = utils.filters, save = utils.save, fetch = utils.fetch;


  export default {
    name: 'app',
    data: function() {
      return {
        todos: fetch(),
        newTodo: '',
        editing: null,
        visibility: 'all'
      }
    },
    watch: {
      todos: {
        deep: true,
        handler: save
      }
    },
    computed: {
      filteredTodos: function () {
        return filters[this.visibility](this.todos);
      },
      remaining: function () {
        return filters.active(this.todos).length;
      },
      allDone: {
        get: function () {
          return this.remaining === 0;
        },
        set: function (value) {
          this.todos.forEach((todo) => todo.completed = value);
        }
      }
    },
    created: function() {
      bus.$on('editTodo', this.editTodo);
      bus.$on('doneEdit', this.doneEdit);
      bus.$on('cancelEdit', this.cancelEdit);
      bus.$on('removeTodo', this.removeTodo);
      bus.$on('removeCompleted', this.removeCompleted);
      bus.$on('router', this.setVisibility);
    },
    methods: {
      addTodo: function() {
        this.todos.push({
          id: uuid(),
          title: this.newTodo && this.newTodo.trim(),
          completed: false
        });
        this.newTodo = '';
      },
      removeTodo: function(todo) {
        let index = this.todos.indexOf(todo);
        if (index > -1) {
          this.todos.splice(this.todos.indexOf(todo), 1);
        }
      },
      editTodo: function(todo) {
        this.beforeEditCache = todo.title;
        this.editing = todo;
      },
      doneEdit: function(todo) {
        this.editing = null;
        if (!todo.title.trim()) {
          this.removeTodo(todo);
        }
      },
      cancelEdit: function(todo) {
        this.editing = null;
        todo.title = this.beforeEditCache;
      },
      removeCompleted: function() {
        this.todos = filters.active(this.todos);
      },
      setVisibility: function(visibility) {
        this.visibility = visibility;
      }
    },
    components: {
      todoItem,
      todoFooter
    }
  }
</script>
